
spring:
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ${SPRING_APPLICATION_NAME:sleuth-client}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
my.next.services: ${MY_NEXT_SERVICES:}
logging.level.org.springframework.cloud.sleuth: DEBUG
debug: true
server:
  port: 8084