spring:
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ${SPRING_APPLICATION_NAME:sleuth-client}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
my.next.services: ${MY_NEXT_SERVICES:}
logging.level.org.springframework.cloud.sleuth: DEBUG
debug: true