
spring:
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ${SPRING_APPLICATION_NAME:sleuth-client}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: MyConfig
eureka:
  client:
    serviceUrl:
      defaultZone: http://${BOOT_EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

my.next.services: ${MY_NEXT_SERVICES:}
logging.level.org.springframework.cloud.sleuth: DEBUG
debug: true

server:
  port: 8080