server:
  port: 9411

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  sleuth:
    enabled: false
  application:
    name: zipkin
eureka:
  client:
    serviceUrl:
      defaultZone: http://${BOOT_EUREKA_SERVER:localhost}:8761/eureka/
zipkin:
  store:
    type: mem

endpoints.health.sensitive: false
endpoints.default.web.enabled: true
management.security.enabled: false
management.endpoints.web.base-path: /admin